---
title: "chapter4-단원문제"
author: "jeong"
date: '2021 4 23 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 연습문제01
### 1부터 100까지의 수 중에서 3의 배수이면서 4의 배수는 아닌 수의 합을 구하라.
```{r}
test <-c(1:100)
aa <- test[test%%3==0 & test%%4!=0]
sum(aa)
```

## 연습문제02
### x와 n을 입력하면 1부터 n까지의 수 중에서 x의 배수 합을 구해주는 사용자 정의 함수를 만들어라.
```{r}
sum <- 0
fact <- function(x,n) {
    for (i in 1:n) {
        if (i %% x==0 ) {
            sum <- sum + i    
        }
    }
    print(sum)
}
```

## 연습문제03
### install.packages("hflights")와 library(hflights)명령어를 이용하여 hflights 데이터를 활용할 수 있게 하자. hflights 데이터에는 총 몇개의 NA가 존재하는가?
```{r}
library(hflights)
sum(is.na(hflights))

```

## 연습문제04
### hflights 데이터에서 비행시간이 가장 긴 데이터는 몇 시간 몇 분인가?
```{r}
c <- max(na.omit(hflights$AirTime))
paste(c,'분')
```

## 연습문제05
### hflights 데이터에서 비행거리가 가장 긴 데이터는 몇 마일인가?
```{r}
s <- max(na.omit(hflights$Distance))
paste(s,'mile')
```

## 연습문제06
### hflights 데이터에서 비행편이 취소된 건수는 몇 건인가?
```{r}
b <- sum(na.omit(hflights$Cancelled))
paste(b,'건')
```

